# This is a basic workflow to help you get started with Actions
# Ref: https://stackoverflow.com/a/69465861/3016570

name: Archive Webpage

# Controls when the workflow will run
on:
  issues:
      types: [opened]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.8 # Install the python version needed
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run specific commands # Another step name
        run: |
          ls -lha
          echo "This is a shell command"
          
      - name: Execute Python script # Run with open issue title (the url to archive)
        run: python main.py $TITLE $AUTHOR $OWNER
        env: 
          TITLE: ${{ github.event.issue.title }}
          AUTHOR: ${{ github.event.issue.user.login }}
          OWNER: ${{ github.repository_owner }}
          WBSECRET: ${{ secrets.WAYBACK_S3_SECRET }}
          WBACCESS: ${{ secrets.WAYBACK_S3_ACCESS }}
      
      - name: Push Changes Back To Repo
        uses: GuillaumeFalourd/git-commit-push@v1.3
        
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Archived. Closing issue
